apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cloudinstances.connection-hub.roboscale.io
  annotations:
    cert-manager.io/inject-ca-from: '{{ .Release.Namespace }}/{{ include "connection-hub-operator.fullname"
      . }}-serving-cert'
    controller-gen.kubebuilder.io/version: v0.9.2
  labels:
  {{- include "connection-hub-operator.labels" . | nindent 4 }}
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: '{{ include "connection-hub-operator.fullname" . }}-webhook-service'
          namespace: '{{ .Release.Namespace }}'
          path: /convert
      conversionReviewVersions:
      - v1
  group: connection-hub.roboscale.io
  names:
    kind: CloudInstance
    listKind: CloudInstanceList
    plural: cloudinstances
    singular: cloudinstance
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.gatewayConnection.gatewayResource
      name: Gateway
      type: string
    - jsonPath: .status.gatewayConnection.hostname
      name: Hostname
      type: string
    - jsonPath: .status.gatewayConnection.clusterID
      name: Cluster ID
      type: string
    - jsonPath: .status.phase
      name: Multicast
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CloudInstance is the Schema for the cloudinstances API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: CloudInstanceSpec defines the desired state of CloudInstance
            type: object
          status:
            description: CloudInstanceStatus defines the observed state of CloudInstance
            properties:
              connectionResources:
                properties:
                  clusterStatus:
                    properties:
                      exists:
                        type: boolean
                      name:
                        type: string
                    type: object
                  endpointStatus:
                    properties:
                      exists:
                        type: boolean
                      name:
                        type: string
                    type: object
                type: object
              deployerStatus:
                properties:
                  exists:
                    type: boolean
                  name:
                    type: string
                  phase:
                    type: string
                type: object
              gatewayConnection:
                properties:
                  clusterID:
                    type: string
                  connectionStatus:
                    type: string
                  gatewayResource:
                    type: string
                  hostname:
                    type: string
                type: object
              phase:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []